---
swagger: "2.0"
info:
  description: "It's an example of Spyker Backend API for Picking App\n"
  version: "1.0.0"
  title: "Spryker Backend API - Picking App"
host: "virtserver.swaggerhub.com"
basePath: "/Spryker/spryker-backend-api/1.0.0"
tags:
- name: "orders"
  description: "Everything about Spryker Backend API Orders"
schemes:
- "https"
- "http"
paths:
  /orders:
    get:
      tags:
      - "orders"
      summary: "Get a list of orders"
      operationId: "ordersGET"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/OrderCollection"
        "400":
          description: "Invalid Order"
      x-swagger-router-controller: "Orders"
  /orders/{orderReference}:
    get:
      tags:
      - "orders"
      summary: "Find an order by ID"
      operationId: "ordersOrderReferenceGET"
      produces:
      - "application/json"
      parameters:
      - name: "orderReference"
        in: "path"
        description: "Order reference of an order to be fetched"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Order"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Order not found"
      x-swagger-router-controller: "Orders"
definitions:
  OrderCollection:
    type: "array"
    items:
      $ref: "#/definitions/Order"
  Order:
    type: "object"
    properties:
      id:
        type: "string"
        example: "DE_123456789"
      created_at:
        type: "string"
        format: "datetime"
        example: "2021-01-23T13:42:00+0000"
      order_reference:
        type: "string"
        example: "DE_123456789"
      cusotmer_reference:
        type: "integer"
        format: "int64"
        example: "DE_987654321"
      number_of_items:
        type: "integer"
        example: 5
      grand_total_formatted:
        type: "string"
        example: "$25.41"
      status:
        type: "string"
        example: "ready for picking"
        description: "Order Status"
        enum:
        - "new"
        - "ready for picking"
        - "picked"
        - "ready for collection"
        - "collected"
    xml:
      name: "Order"
    example:
      number_of_items: 5
      order_reference: "DE_123456789"
      created_at: "2021-01-23T13:42:00+0000"
      cusotmer_reference: "DE_987654321"
      id: "DE_123456789"
      grand_total_formatted: "$25.41"
      status: "ready for picking"
